const SUPABASE_URL = 'https://lzulkhmjjmofcizazdxk.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_On2i52EToTlED7YhBp5HCg_VYfvFJiG';
const TARGET_FOLDER_NAME = "To Sort";

// Listen for messages from the Web App to configure the session
chrome.runtime.onMessageExternal.addListener((request, sender, sendResponse) => {
    if (request.action === "set_session") {
        chrome.storage.local.set({
            userId: request.userId,
            email: request.email
        }, () => {
            console.log("Session set:", request.email);
            sendResponse({ success: true });
        });
        return true;
    }
});

// Capture bookmarks
chrome.bookmarks.onCreated.addListener(async (id, bookmark) => {
    // We only care about URLs (avoid folders)
    if (!bookmark.url) return;

    // Check parent folder name
    const nodes = await chrome.bookmarks.get(bookmark.parentId);
    if (!nodes || nodes.length === 0) return;
    const parentFolder = nodes[0];

    if (parentFolder.title === TARGET_FOLDER_NAME) {
        console.log("Captured bookmark in To Sort:", bookmark.title);
        await processBookmark(bookmark);
        // After sending, remove it from the browser to keep it clean
        chrome.bookmarks.remove(id);
    }
});

async function processBookmark(bookmark) {
    const data = await chrome.storage.local.get(['userId']);
    const userId = data.userId;

    if (!userId) {
        console.error("No active session. Please log in via the web app.");
        // We could also trigger a notification here
        return;
    }

    try {
        const payload = {
            user_id: userId,
            url: bookmark.url,
            title: bookmark.title || bookmark.url
            // ai_summary, tags, reminder_date are generated by Supabase Edge Function
        };

        const response = await fetch(`${SUPABASE_URL}/rest/v1/bookmarks`, {
            method: 'POST',
            autoAuth: false,
            headers: {
                'Content-Type': 'application/json',
                'apikey': SUPABASE_ANON_KEY,
                'Authorization': `Bearer ${SUPABASE_ANON_KEY}`, // Using anon key since it's an insert policy controlled by RLS, BUT wait: user_id must match auth.uid()
                // IMPORTANT: If we only have the userId in storage and not the JWT, 
                // the RLS policy "Users can insert their own bookmarks WITH CHECK (auth.uid() = user_id)" 
                // will fail if we use the Anon Key because auth.uid() evaluates to null.

                // For a robust extension, we would need to pass the access_token from the Web App,
                // or have an edge function that allows anon inserts with a token, or adjust RLS.
                // Assuming we use a service key OR we pass the jwt token from the web app.
                // Let's assume the auth token should have been passed in 'set_session'.
            },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            console.error("Failed to push bookmark to Supabase:", await response.text());
        } else {
            console.log("Successfully pushed bookmark!");
        }
    } catch (error) {
        console.error("Network error pushing bookmark:", error);
    }
}
